default:
  serverbase:       'https://mii-agiop-3p.life.uni-leipzig.de/fhir/'
# if you need to authenticate on your fhir server, set username and password
  username:        NULL
  password:        NULL
## TRUE = peer verification anschalten, FALSE = peer verification ausschalten   
  ssl_verify_peer: TRUE